[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."check-tips-scheduled"]
  schedule = "*/30 * * * *"
